Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -42,5 +42,27 @@ jobs:
       shell: bash
       run: mvn package
     - name: Deploy package
-      run: mvn -X deploy -Dtoken=${{ secrets.GITHUB_TOKEN }}
-      
+      run: |
+        function fail {
+          echo $1 >&2
+          exit 1
+        }
+        
+        function retry {
+          local n=1
+          local max=5
+          local delay=15
+          while true; do
+            "$@" && break || {
+              if [[ $n -lt $max ]]; then
+                ((n++))
+                echo "Command failed. Attempt $n/$max:"
+                sleep $delay;
+              else 
+                fail "The command has failed after $n attempts."
+              fi
+            }
+          done
+        }
+        
+        retry `mvn -X deploy -Dtoken=${{ secrets.GITHUB_TOKEN }}`
